### ISSUE TITLE
Initial concept outline

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/dnh-classrooms-plus#1]
## Authentication

* `/login` - Login view for normal users
* `/logout` - Logs a user out

## Account

* `/account` - Account related settings

## Dashboard

* `/` - Dashboard
  * Personalized update message (Good morning ..., you have 5 unread messages, etc.)
  * School schedule of today
  * List of messages
  * List of latest grades

## Schedule

* `/schedule`

## Messages

* `/messages`

## Grades

* `/grades`

**Comment by CubeCard** [comment]
Hallo
